name: Doxygen Workflow

on:
  push:

jobs:
  deploy:
    name: Deploy to github pages
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2

    - run: sudo apt-get install doxygen
    - run: sudo apt-get install graphviz
    - run: doxygen doxconf

    - name: Push git subdir as branch
      uses: s0/git-publish-subdir-action@v2.4.0

    env:
      REPO: self
      BRANCH: gh-pages
      FOLDER: DOCS/html
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}