name: Google Unit Tests

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gtest and cmake
        run: sudo apt install libgtest-dev && sudo apt install cmake 
      
      - name: gtest cmake
        run: cd /usr/src/gtest && sudo cmake . && sudo make

      - name: create symbolic link 1
        run: sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
      - name: create symbolic link 2
        run: sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a 

      - name: Run tests
        run: cd tests && cmake CMakeLists.txt && make ./UnitTests
      