name: Workflow

on: push

jobs:
  memory_leak_test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Installing Valgrind
          run: sudo apt-get install valgrind
        - name: build
          run: make build
        - name: Checking memory leak
          run: make valgrind

  code_analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing cppcheck
        run: sudo apt-get install cppcheck 
      - name: Code analysis
        run: make cppcheck
      - name: Artifact performance
        uses: actions/upload-artifact@v2
        with:
          path: ./performance_warnings.txt
      - name: Artifact style
        uses: actions/upload-artifact@v2
        with:
          path: ./style_warnings.txt

  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gtest and cmake
        run: sudo apt install libgtest-dev && sudo apt install cmake 
      
      - name: create test env
        run: cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make

      - name: create symbolic link 1
        run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
      - name: create symbolic link 2
        run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a 

      - name: compile
        run: g++ -std=c++17 *.cpp

      - name: cmake CMakeLists
        run: cmake tests/CMakeLists.txt

      - name: build test
        run: cd tests && make
        
      - name: run test
        run: tests/unit_tests

  in-out_test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - run: g++-10 -std=c++17 -Wall *.cpp -o main

      - name: Set permission
        run: chmod +x ./run_tests.sh

      - name: generate output
        run: ./run_tests.sh

      - name: cat output
        run: cat output1.txt && cat output2.txt

      - name: check output
        run: diff output1.txt good_output1.txt && diff output2.txt good_output2.txt

  google_unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install gtest and cmake
        run: sudo apt install libgtest-dev && sudo apt install cmake 
      
      - name: create test env
        run: cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make

      - name: create symbolic link 1
        run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest.a
      - name: create symbolic link 2
        run: sudo ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a 

      - name: compile
        run: g++ -std=c++17 *.cpp

      - name: cmake CMakeLists
        run: cmake tests/CMakeLists.txt

      - name: build test
        run: cd tests && make
        
      - name: run test
        run: tests/unit_tests