name: Workflow

on: push

jobs:
  memory_leak_test:
    runs-on: ubuntu-latest
    container: holdmedve/mosze:latest
    steps:
        - uses: actions/checkout@v2

        - name: Build
          run: make build
        - name: Checking memory leak
          run: make valgrind

  code_analysis:
    runs-on: ubuntu-latest
    container: holdmedve/mosze:latest
    steps:
      - uses: actions/checkout@v2

      - name: Code analysis
        run: make cppcheck
      - name: Artifact performance
        uses: actions/upload-artifact@v2
        with:
          path: ./performance_warnings.txt
      
      - name: Artifact style
        uses: actions/upload-artifact@v2
        with:
          path: ./style_warnings.txt

  documentation:
    runs-on: ubuntu-latest
    container: holdmedve/mosze:latest
    steps:
      - uses: actions/checkout@master

      - name: Generate documentation
        run: make documentation
      
      - name: Push git subdir as branch
        uses: s0/git-publish-subdir-action@v2.4.0

        env:
            REPO: self
            BRANCH: gh-pages
            FOLDER: DOCS/html
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  google_unit_test:
    runs-on: ubuntu-latest
    container: holdmedve/mosze:latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Build unit tests
        run: make make_unittests
        
      - name: Run unit tests
        run: make run_unittests

  
  in_out_tests:
    runs-on: ubuntu-latest
    container: holdmedve/mosze:latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make build
      
      - name: In-out tests
        run: make run_in_out_tests